"""add-slug-field-to-products-table

Revision ID: 318a533b587a
Revises: 1021f771bb7b
Create Date: 2025-12-10 12:29:41.135607

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "318a533b587a"
down_revision: Union[str, Sequence[str], None] = "1021f771bb7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("slug", sa.String(length=200), nullable=False))
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_column("products", "slug")
    # ### end Alembic commands ###
